### ISSUE TITLE
Missing Recipe

### ISSUE THREAD

**Issue by Sailingway** [LimonBlaze/Respiteful#15]
The hot cocoa recipe from farmer's respite does not accept the milk bottles from neapolitan. Since this mod is supposed to bridge the gap between these mods I thought it should be fixed by you.

**Comment by RaymondBlaze** [comment]
This has been resolved by Farmer's Respite itself in the 1.20.1 update by moving to use fluids, since I've stopped supporting 1.19.2, marking this as closed.
