### ISSUE TITLE
[1.20.1] Loading Create with Respiteful disables JEI recipes for most recipe types from Create

### ISSUE THREAD

**Issue by flynnvali** [LimonBlaze/Respiteful#16]
Tested in a save with just Create, JEI, Farmer's Delight, Farmer's Respite, Neapolitan, Blueprint, and Respiteful with the latest versions of all of the above. Disabling just Respiteful returns the recipes to being viewable in JEI, no idea what's causing it. The recipes still function in-game, it's purely in JEI that it does not appear.
 
All recipes types from Create alone are not visible except for Sawing and Deploying. It seems as if other custom recipes from other mods besides Create are unaffected, but I cannot be certain of this.

**Comment by evanbones** [comment]
Confirmed. Just narrowed the issue down to this mod as well. If only I'd seen this before spending half an hour removing mods. D'oh!

**Comment by RaymondBlaze** [comment]
This is quite strange, Respiteful has no code interaction with Create or JEI.
The only suspect here would be the Registrate that both Respiteful and Create used as a dependency, where Respiteful used and bundled a higher version of it, that could be the problem.
I'll be building a jar with the same version of that Create used, and see if that could resolve the problem.

**Comment by RaymondBlaze** [comment]
Fixed in 1.2.1 by reverting to Registrate 1.3.3.

**Comment by KooBaby** [comment]
what the hell is Registrate???
