### ISSUE TITLE
Recipe errors 

### ISSUE THREAD

**Issue by Tosh022402** [LimonBlaze/Respiteful#2]
All recipes for ice cream blocks give 1 ice cream block instead of 8 

Also the recipes for Snow top teas and coffee only give 1 of them even tho you use 3 bottles

**Comment by Tosh022402** [comment]
![image](https://user-images.githubusercontent.com/92280867/225697313-ddf7643b-ac32-4107-9bc7-779f4d03614d.png)
![image](https://user-images.githubusercontent.com/92280867/225697433-094516c7-97bf-42ba-b6e5-d86cc7ff98e8.png)
these are neapolitan´s recipes

**Comment by RaymondBlaze** [comment]
Fixed in 1.1.0
