### ISSUE TITLE
Crash on Magma Server

### ISSUE THREAD

**Issue by ghost** [LimonBlaze/Respiteful#9]
With Mods:blueprint-1.18.2-5.5.0,FarmersDelight-1.18.2-1.2.1,FarmersRespite-1.18.2-1.3.0,neapolitan-1.18.2-3.0.0 and respiteful-1.18.2-1.1.0-patch.1
Here's [log:](https://paste.ubuntu.com/p/fNXKZjVh78/)

**Comment by ghost** [comment]
Here's log:[https://paste.ubuntu.com/p/fNXKZjVh78/](https://paste.ubuntu.com/p/fNXKZjVh78/)

**Comment by MarbleGateKeeper** [comment]
> Please send this info to the Magma team on Discord or GitLab
Please also include the full log file!

I think it's a problem of magma itself since I cannot reproduce it.
